# Site settings

title: Y4iT

baseurl: http://toffmendoza.me/sandbox-y4it
#baseurl: https://y4it.org/

# Build settings
markdown: kramdown
permalink: pretty

urlOfficial: "https://y4it.org/"
urlFacebook: "https://www.facebook.com/ilove.Y4iT/"
urlTwitter: "https://twitter.com/y4it"
urlInstagram: "https://www.instagram.com/y4it/"
urlYouTube: "https://www.youtube.com/user/iloveY4iT"
urlSnapchat: "https://www.snapchat.com/add/y4it"
urlViber: "http://chats.viber.com/y4it"

organizerDescription:
 - "The UP System Information Technology Foundation (UPSITF) Inc. is a non-government organization focused on the application of Information and Communication Technology for development. It partners with UP Information Technology Development Center in providing various services such as, but not limited to, Education Development, IT Human Capital Development, Research &amp; Development, Software Engineering, ICT Policy Development and Planning, and IT Project Management."
